# Generated by Django 4.1.5 on 2023-02-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
