# Generated by Django 4.1.5 on 2023-02-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositslip',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='withdrawalslip',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
